[pytest]

# ✅ Opciones que se ejecutan automáticamente
addopts = 
        -v
        -s
        --html=reports/report.html 
        --self-contained-html
# ✅ Personalización del reporte HTML, no  aplica  en  versiones  modernas
#html_report_title = TalentoLab – Resumen de ejecución
#html_report_description = Suite UI + API completa
